import { WorkoutTemplate } from './types';

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'push-day',
    name: 'Día de Empuje',
    duration: 55,
    difficulty: 'Intermedio',
    category: 'Fuerza',
    image: 'https://picsum.photos/seed/push/800/600',
    exercises: [
      {
        id: 'bench-press',
        name: 'Press de banca',
        sets: 4,
        reps: '8-10',
        rest: 90,
        muscleGroup: 'Pecho',
        image: 'https://picsum.photos/seed/bench/400/300',
      },
      {
        id: 'overhead-press',
        name: 'Press militar',
        sets: 3,
        reps: '10-12',
        rest: 60,
        muscleGroup: 'Hombros',
        image: 'https://picsum.photos/seed/overhead/400/300',
      },
      {
        id: 'incline-db-press',
        name: 'Press inclinado con mancuernas',
        sets: 3,
        reps: '12',
        rest: 60,
        muscleGroup: 'Pecho',
        image: 'https://picsum.photos/seed/incline/400/300',
      },
      {
        id: 'lateral-raises',
        name: 'Elevaciones laterales',
        sets: 4,
        reps: '15',
        rest: 45,
        muscleGroup: 'Hombros',
        image: 'https://picsum.photos/seed/lateral/400/300',
      },
      {
        id: 'tricep-pushdown',
        name: 'Extensiones de tríceps',
        sets: 3,
        reps: '12-15',
        rest: 45,
        muscleGroup: 'Tríceps',
        image: 'https://picsum.photos/seed/tricep/400/300',
      },
    ],
  },
  {
    id: 'pull-day',
    name: 'Día de Tirón',
    duration: 50,
    difficulty: 'Intermedio',
    category: 'Fuerza',
    image: 'https://picsum.photos/seed/pull/800/600',
    exercises: [
      {
        id: 'deadlift',
        name: 'Peso muerto',
        sets: 3,
        reps: '5',
        rest: 180,
        muscleGroup: 'Espalda',
        image: 'https://picsum.photos/seed/deadlift/400/300',
      },
      {
        id: 'pull-ups',
        name: 'Dominadas',
        sets: 3,
        reps: 'Al fallo',
        rest: 90,
        muscleGroup: 'Espalda',
        image: 'https://picsum.photos/seed/pullups/400/300',
      },
      {
        id: 'barbell-row',
        name: 'Remo con barra',
        sets: 4,
        reps: '8-10',
        rest: 90,
        muscleGroup: 'Espalda',
        image: 'https://picsum.photos/seed/row/400/300',
      },
      {
        id: 'face-pulls',
        name: 'Face pulls',
        sets: 3,
        reps: '15',
        rest: 45,
        muscleGroup: 'Hombros',
        image: 'https://picsum.photos/seed/facepull/400/300',
      },
      {
        id: 'bicep-curls',
        name: 'Curl de bíceps',
        sets: 3,
        reps: '12',
        rest: 60,
        muscleGroup: 'Bíceps',
        image: 'https://picsum.photos/seed/bicep/400/300',
      },
    ],
  },
  {
    id: 'leg-day',
    name: 'Día de Piernas',
    duration: 60,
    difficulty: 'Avanzado',
    category: 'Fuerza',
    image: 'https://picsum.photos/seed/legs/800/600',
    exercises: [
      {
        id: 'squats',
        name: 'Sentadillas',
        sets: 4,
        reps: '6-8',
        rest: 120,
        muscleGroup: 'Piernas',
        image: 'https://picsum.photos/seed/squat/400/300',
      },
      {
        id: 'leg-press',
        name: 'Prensa de piernas',
        sets: 3,
        reps: '10-12',
        rest: 90,
        muscleGroup: 'Piernas',
        image: 'https://picsum.photos/seed/legpress/400/300',
      },
      {
        id: 'leg-curls',
        name: 'Curl femoral',
        sets: 3,
        reps: '12-15',
        rest: 60,
        muscleGroup: 'Piernas',
        image: 'https://picsum.photos/seed/legcurl/400/300',
      },
      {
        id: 'calf-raises',
        name: 'Elevación de talones',
        sets: 4,
        reps: '15-20',
        rest: 45,
        muscleGroup: 'Piernas',
        image: 'https://picsum.photos/seed/calf/400/300',
      },
    ],
  },
  {
    id: 'cardio-hiit',
    name: 'Cardio HIIT',
    duration: 30,
    difficulty: 'Principiante',
    category: 'Cardio',
    image: 'https://picsum.photos/seed/cardio/800/600',
    exercises: [
      {
        id: 'burpees',
        name: 'Burpees',
        sets: 4,
        reps: '45 seg',
        rest: 15,
        muscleGroup: 'Cuerpo completo',
        image: 'https://picsum.photos/seed/burpee/400/300',
      },
      {
        id: 'mountain-climbers',
        name: 'Escaladores',
        sets: 4,
        reps: '45 seg',
        rest: 15,
        muscleGroup: 'Core',
        image: 'https://picsum.photos/seed/climber/400/300',
      },
      {
        id: 'jumping-jacks',
        name: 'Jumping Jacks',
        sets: 4,
        reps: '45 seg',
        rest: 15,
        muscleGroup: 'Cardio',
        image: 'https://picsum.photos/seed/jacks/400/300',
      },
    ],
  },
  {
    id: 'upper-body',
    name: 'Tren Superior',
    duration: 45,
    difficulty: 'Intermedio',
    category: 'Fuerza',
    image: 'https://picsum.photos/seed/upper/800/600',
    exercises: [
      {
        id: 'push-ups',
        name: 'Flexiones',
        sets: 3,
        reps: '15-20',
        rest: 60,
        muscleGroup: 'Pecho',
        image: 'https://picsum.photos/seed/pushups/400/300',
      },
      {
        id: 'chin-ups',
        name: 'Dominadas supinas',
        sets: 3,
        reps: '8-10',
        rest: 90,
        muscleGroup: 'Espalda',
        image: 'https://picsum.photos/seed/chinups/400/300',
      },
      {
        id: 'dips',
        name: 'Fondos',
        sets: 3,
        reps: '10-12',
        rest: 60,
        muscleGroup: 'Tríceps',
        image: 'https://picsum.photos/seed/dips/400/300',
      },
    ],
  },
];
